### ISSUE TITLE
Polling mode based on timestamp

### ISSUE THREAD

**Issue by srkpers** [SAP/kafka-connect-sap#100]
I was trying to do polling based on timestamp (timestamp.column.name) and got an error. I then checked the documentation and looks like only "bulk" and "incrementing" are supported at this point.
Any idea when "timestamp" based polling to detect changes will be supported? This will be really helpful as we do not have any HANA table with strictly incrementing values for any column which leaves us with only one option to stream data which is "query" based. With query based approach we will not be able to get data into Kafka in near real time.

**Comment by elakito** [comment]
It's been more than a month since last activity, so I suppose we can close this ticket.
