### ISSUE TITLE
How to automatically create tables instead of topics

### ISSUE THREAD

**Issue by Sano123456** [SAP/kafka-connect-sap#12]
Hi
i used this plugin and sucessufly connected to sap but i need to know how can i persist the data in tables instead of streaming them on topics

let me know
thanks very much

**Comment by sbcd90** [comment]
Hi @Sano123456 ,
I didnt get your question fully.
This connector currently allows you to persist data in SAP Hana tables.
In case you're asking for automatic creation of new tables & then persisting of data, 
there is an option for sink

```
auto.create=true
```
Please let me know if it answers your question.

**Comment by elakito** [comment]
I think the question was answered.
