### ISSUE TITLE
Incementing Mode with Timestamp Field not working correctly

### ISSUE THREAD

**Issue by AndreasKlein** [SAP/kafka-connect-sap#121]
Hi @elakito, 
we are observing some unintended behavior when using the incrementing mode with a column of type TIMESTAMP. Since Hana's timestamp does not contain timezone information the timestamps are persisted in UTC. 
However when polling in incr. mode the offset persisted for the next poll is off by exactly the timezone offset to UTC. For me being in CET that is currently 1 hour. That means another change on the same row will not be detected if it happens within that hour.

Example: 
- Timestamp Field `LAST_MODIFIED` is set to `2022-02-08 19:45:54.623000000`. 
- First Poll does a comparison `... WHERE LAST_MODIFIED > '1970-01-01 00:00:00.000'`.
- The row is selected
- Message is sent to Kafka
- Offset is persisted `{"LAST_MODIFIED":"2022-02-08 20:45:54.623"}`
- A change is persisted: `LAST_MODIFIED` is now let's say: `2022-02-08 19:47:00.000000000`. 
- the next poll happens with where clause: `... WHERE LAST_MODIFIED > '2022-02-08 20:45:54.623'`
- no results found, the change is skipped

I tracked it down to this: 
```
case java.sql.Types.TIMESTAMP => resultSet.getTimestamp(index, calendarUTC)
```
where `calendarUTC` is `Calendar.getInstance(TimeZone.getTimeZone("UTC"))`. (https://github.com/SAP/kafka-connect-sap/blob/master/src/main/scala/com/sap/kafka/client/hana/HANAJdbcClient.scala#L508)

It seems that providing the calendar instance with UTC is causing the issue. Setting the Calendar to local TZ with `.getDefault()` or skipping the second argument of `.getTimestamp` results in the expected behavior, meaning (in the numbers the example above) that `2022-02-08 19:45:54.623` would be saved as offset and no rows would be skipped. 
I have tried this in multiple timezones and it confirmed the observed outcome. E.g. being in GMT+4 and using `calendarUTC` resulted in offset `2022-02-08 23:45:54.623`, using default timezone worked correctly.

What strikes me is that `calendarUTC` had been added a while ago to address date issues: https://github.com/SAP/kafka-connect-sap/commit/8a45677bbfcf357638ca1fd5228f223290594052

The docs on java.sql's Resulset.getTimestamp is a little unclear to me, so that did not help much.

> Retrieves the value of the designated column in the current row of this ResultSet object as a java.sql.Timestamp object in the Java programming language. This method uses the given calendar to construct an appropriate millisecond value for the timestamp if the underlying database does not store timezone information.

However it seems like providing UTC, when the DB entry is in UTC leads to a timestamp in local time, which then is used without re-adjusting for the following query, where it should be have been in UTC again. I suggest having the local time timestamp is not beneficial, storing and handling it in UTC all the way would be cleaner.

What are your thoughts on this?

Maybe this is related to: https://github.com/SAP/kafka-connect-sap/issues/106

**Comment by elakito** [comment]
@AndreasKlein Indeed getTimestamp(index, UTC) doesn't seem to return the value expected on at least one system that I tried. I am in discussion with our HANA JDBC colleagues...

**Comment by AndreasKlein** [comment]
Ok thanks, looking at the PG JDBC implementation, it looks like incorrect behavior in the ngdbc, adding a calUTC as second argument should return the timestamp with UTC time.

**Comment by elakito** [comment]
@AndreasKlein Our HANA colleague helped to clarify the behavior. We were storing the UTC timestamp value using setTimestamp(n, value), which will store the value converted to the local time. Later, when this value is read with getTimestamp(n, UTC), this incorrectly converted value is read as UTC. So, to avoid this problem, use UTC for both storing and retrieving.

**Comment by AndreasKlein** [comment]
Hi @elakito it's not entirely clear to which "storing the UTC timestamp" you are referring. Do you mean to storing of the offset? Would you mind hopping on a quick call to discuss the details? Thanks

**Comment by elakito** [comment]
@AndreasKlein This fix itself should fix the previous inconsistency in writing (i.e., setTimestamp) and reading (i.e., getTimestamp) the timestamp value. It now uses UTC in both places so that there is no timezone conversion when writing or reading timestamp values. However, I saw the incremental query code has  string conversion in several places and it may still be querying with the wrong value. I haven't cleaned up this part.

**Comment by elakito** [comment]
@AndreasKlein I added the fix for the incremental query to the linked PR, which should fix the problem.

**Comment by AndreasKlein** [comment]
@elakito Great, I'll try to get this tested for our use case asap
