### ISSUE TITLE
HANA sink connector is not working

### ISSUE THREAD

**Issue by srkpers** [SAP/kafka-connect-sap#123]
Tested the below scenario and unable to get HANA Sink connector to work.

- Create table in HANA and populate with few rows
CREATE COLUMN TABLE "ZSKTEST2" ("ID" INTEGER NOT NULL, "MANDT" NVARCHAR(3) NOT NULL, "FIRSTNAME" NVARCHAR(20) NOT NULL, "LASTNAME" NVARCHAR(20) NOT NULL);
- Use  HANA Source connector to replicate HANA table to Kafka topic --> This worked
- Use  HANA Sink connector to replicate Kafka topic to HANA table in a difference schema --> This failed

Sample message in Kafka topic (file attached)

Got the below error when connector tried to create HANA table. This was when the auto create parameter in connector config was set to true. Looks like the sql command formulated by the HANA Sink connector to create the table has issue as it is not having any field names.

[INFO] 2022-02-10 16:25:40,571 [task-thread-bw1-hana-source-and-sink-test2-0] com.sap.kafka.client.hana.HANAJdbcClient $anonfun$createTable$1 - Creating table:ZSKTEST2 with SQL: CREATE COLUMN TABLE "KAFKA"."ZSKTEST2" ()
[ERROR] 2022-02-10 16:25:40,619 [task-thread-bw1-hana-source-and-sink-test2-0] com.sap.kafka.client.hana.HANAJdbcClient $anonfun$createTable$1 - Error during table creation
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [257] (at 41): sql syntax error: incorrect syntax near ")": line 1 col 41 (at pos 41)

Also tried by creating the target table in HANA manually and got the below error in connector log

[INFO] 2022-02-10 16:29:17,386 [task-thread-bw1-hana-source-and-sink-test2-0] com.sap.kafka.connect.sink.hana.HANASinkTask put - PHASE - 1 ended for task, with assigned partitions [bw1-hana-source-test2-0]
[ERROR] 2022-02-10 16:29:17,386 [task-thread-bw1-hana-source-and-sink-test2-0] org.apache.kafka.connect.runtime.WorkerSinkTask deliverMessages - WorkerSinkTask{id=bw1-hana-source-and-sink-test2-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Table "KAFKA"."ZSKTEST2" has an incompatible schema to the record Schema.
Auto Evolution of schema is not supported
com.sap.kafka.utils.SchemaNotMatchedException: Table "KAFKA"."ZSKTEST2" has an incompatible schema to the record Schema.
Auto Evolution of schema is not supported
[Sample message.txt](https://github.com/SAP/kafka-connect-sap/files/8042680/Sample.message.txt)

**Comment by srkpers** [comment]
Did further testing by using the below example
https://github.com/SAP/kafka-connect-sap/blob/master/examples/inventory7db/README.md
Debezium MySQL Source connector is replicating from MySQL database table to Kafka topic
HANA Sink connector is replicating the Kafka topic to HANA Database table
Test scenario
1. Initial replication worked. The table got created in HANA and the number of messages from Kafka topic got created as number of rows in HANA table
2. Inserted a row in MySQL table and it made it to HANA table
3. Updated a row in MySQL table and saw the same row got updated in HANA table
4. Deleted a row in MySQL table and noticed the __deleted field in the HANA table did not get updated to "true". It is still showing as "false". So the delete thing did not work.
**Here are the logs from the HANA Sink connector corresponding to the Delete.**

INFO] 2022-02-11 02:19:39,331 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test1-0] com.sap.kafka.connect.sink.hana.HANASinkTask put - Number of Records read for Sink: 2
[INFO] 2022-02-11 02:19:39,331 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test1-0] com.sap.kafka.connect.sink.hana.HANAWriter write - write records to HANA
[INFO] 2022-02-11 02:19:39,331 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test1-0] com.sap.kafka.connect.sink.hana.HANAWriter write - initialize connection to HANA
[INFO] 2022-02-11 02:19:39,333 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test1-0] com.sap.kafka.connect.sink.hana.HANASinkTask add - Table "MYSQLDOC2"."ZPERSONS" exists. Validate the schema and check if schema needs to evolve
[INFO] 2022-02-11 02:19:39,334 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test1-0] com.sap.kafka.connect.sink.hana.HANAWriter flush - flush records into HANA
[INFO] 2022-02-11 02:19:39,334 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test1-0] com.sap.kafka.client.hana.AbstractHANAPartitionLoader prepareInsertIntoStmt - Creating prepared statement: UPSERT "MYSQLDOC2"."ZPERSONS" ("persons_id", "first_name", "last_name", "__deleted") VALUES (?, ?, ?, ?) WITH PRIMARY KEY
[INFO] 2022-02-11 02:19:39,336 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test1-0] com.sap.kafka.client.hana.AbstractHANAPartitionLoader $anonfun$loadPartition$3 - **Skipping update for the to-be-deleted record**
[WARN] 2022-02-11 02:19:39,336 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test1-0] com.sap.kafka.client.hana.AbstractHANAPartitionLoader $anonfun$loadPartition$3 - Missing schema for the tombstone record
[INFO] 2022-02-11 02:19:39,337 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test1-0] com.sap.kafka.connect.sink.hana.HANAWriter write - flushing records to HANA successful
[INFO] 2022-02-11 02:19:39,337 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test1-0] com.sap.kafka.connect.sink.hana.HANASinkTask put - PHASE - 1 ended for task, with assigned partitions [mysqldocker2.mysqldb.zpersons-0]

The above connector logs indicate it skipped the update for the to-be-deleted record

**Comment by srkpers** [comment]
Small correction. The above test had delete enabled parameter as "true". I had wrongly stated that it was set to "false". So with that parameter set as "true" the record from HANA table should have got deleted but it did not.
You can see in the connector log that it formulated an UPSERT statement instead of a DELETE statement.
I then tested by setting delete enabled parameter as "false" and that worked as per the documentation. The __deleted field value changed from "false" to "true" for the deleted record. The record itself did not get deleted which is what the documentation also says.

**So if we set the deleted enabled parameter as "true" then the HANA record is not getting deleted as it is forming an UPSERT statement instead of DELETE statement. Let me know if any additional information is needed to fix this issue? Thank you.**

**Comment by elakito** [comment]
@srkpers Thank you for reporting this problem. It seems there was some change introduced in some recent version of debezium such as 1.7.0.Final and this is causing this problem. With debezium 1.4.2.Final, the version that we tested previously, the deletion still works with the current 0.9.3-SNAPSHOT sink connector. You could also try the older version of inventory7db [docker-compose.yaml](https://github.com/SAP/kafka-connect-sap/blob/ed8c5b3c3bfd1e64da3c234dd8b5335ba2991fb2/examples/inventory7db/docker-compose.yaml) which uses debezium 1.4.2.Final). 

I'll try to find out why the sink connector doesn't work with debezium 1.7.0.Final.

**Comment by elakito** [comment]
@srkpers The deletion logic is tied to how debezium source connector generates records. For each record deleted, there is one record which has __deleted=true and a tombstone message that has an empty body but has the key schema value set.
So, when you execute a single record deletion. You should see
Number of Records read for Sink: 2

**Comment by srkpers** [comment]
@elakito I can see that 2 records are produced by Debezium MySQL Source connector for delete in MySQL table and also see 2 records are read by the HANA Sink connector. I have attached a file with entire HANA Sink connector log entries and below listed just the ones which are imporatant parameters related with how the tombstone and delete records will be handled.

"auto.create": "true",
"auto.evolve": "true",
"mysqldocker2.mysqldb.zpersons.table.name": "\"MYSQLDOC2\".\"ZPERSONS\"",
"mysqldocker2.mysqldb.zpersons.table.type": "column",
"mysqldocker2.mysqldb.zpersons.insert.mode": "upsert",
"mysqldocker2.mysqldb.zpersons.delete.enabled": "true",
"mysqldocker2.mysqldb.zpersons.pk.fields": "persons_id",
"mysqldocker2.mysqldb.zpersons.pk.mode": "record_key",
"transforms": "unwrap",
"transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
"transforms.unwrap.drop.tombstones": "false",
"transforms.unwrap.delete.handling.mode": "none",

[HANA_Sink_Connector_config.txt](https://github.com/SAP/kafka-connect-sap/files/8057991/HANA_Sink_Connector_config.txt)

Here are the HANA log entries

[INFO] 2022-02-14 04:51:52,626 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test2-0] com.sap.kafka.connect.sink.hana.HANASinkTask put - **Number of Records read for Sink: 2**
[INFO] 2022-02-14 04:51:52,626 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test2-0] com.sap.kafka.connect.sink.hana.HANAWriter write - write records to HANA
[INFO] 2022-02-14 04:51:52,626 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test2-0] com.sap.kafka.connect.sink.hana.HANAWriter write - initialize connection to HANA
[INFO] 2022-02-14 04:51:52,628 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test2-0] com.sap.kafka.connect.sink.hana.HANASinkTask add - Table "MYSQLDOC2"."ZPERSONS" exists. Validate the schema and check if schema needs to evolve
[INFO] 2022-02-14 04:51:52,628 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test2-0] com.sap.kafka.connect.sink.hana.HANAWriter flush - flush records into HANA
[INFO] 2022-02-14 04:51:52,629 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test2-0] com.sap.kafka.client.hana.AbstractHANAPartitionLoader prepareInsertIntoStmt - Creating prepared statement: **UPSERT "MYSQLDOC2"."ZPERSONS" ("persons_id", "first_name", "last_name") VALUES (?, ?, ?) WITH PRIMARY KEY**
[WARN] 2022-02-14 04:51:52,630 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test2-0] com.sap.kafka.client.hana.AbstractHANAPartitionLoader $anonfun$loadPartition$3 - **Missing schema for the tombstone record**
[WARN] 2022-02-14 04:51:52,630 [task-thread-bw1-mysqldocker-to-hana-sink-avro-test2-0] com.sap.kafka.client.hana.AbstractHANAPartitionLoader $anonfun$loadPartition$3 - Missing schema for the tombstone record

So the "Missing schema for the tombstone record" message is there. Not sure why. The table has Primary key and I can see the Tombstone record in the kafka topic has the Key with primary key. I have taken screenshot of the Tombstone message and provided that in the attached word document
[Tombstone_record_in_Kafka_topic.docx](https://github.com/SAP/kafka-connect-sap/files/8058017/Tombstone_record_in_Kafka_topic.docx)

If I use "rewrite" for delete handling mode then additional column called "__deleted" is getting created in the HANA table and that has value "true" or "false". By default it will have "false" and if a record is deleted then it will have a value of "true". This is working as it is supposed to.

**Comment by elakito** [comment]
@srkpers I don't know why there is no key schema included. Are you using MySQL debezium connector? Could you configure the transformation at the source connector by adding the below parameters to the source connector's configuration.
```
    "transforms": "unwrap",
    "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
    "transforms.unwrap.drop.tombstones": "false",
    "transforms.unwrap.delete.handling.mode": "rewrite"

```

and dump the messages placed in the kafka topic <topic> for a single insert followed by a single delete which deletes this row? For example, you can run this command to dump the messages with the key.
`kafka-console-consumer.sh --bootstrap-server <bootstrap-server> --topic <topic>  --property print.key=true`

There should be three messages. Do all of them include the key schema?

**Comment by srkpers** [comment]
@elakito Right. I have configured "transforms.unwrap.delete.handling.mode": "none", so there is no column called "__deleted".
The deletion of row in HANA table worked as expected. I will do some additional testing but will go ahead and close this issue.
**Thank you for all the input to get this sorted out.**
