### ISSUE TITLE
Kafka 3.0.0 compatibility

### ISSUE THREAD

**Issue by thibthibus** [SAP/kafka-connect-sap#127]
Hi,

Not an issue, just a quick update. We upgraded our Kafka clusters to Kafka 3.0.0 / Strimzi 0.26 . The connector in release 0.9.1 (Scala 2.13 version) is working fine. Compatibility Matrix could then be updated accordingly.
Maybe also add that for those who are using Strimzi to manage their Kafka resources, one must use the Scala 2.12 release of the connector when using Strimzi < 0.25 and the Scala 2.13 release of the connector when using Strimzi >= 0.25.

Regards,

Thibaut

**Comment by elakito** [comment]
@thibthibus Thanks for the information. That is very helpful for the users. If you could create a pull request to update the documentation, that would be great. Thanks.

**Comment by elakito** [comment]
@thibthibus  Thanks for the PR.
#128 merged
