### ISSUE TITLE
Writing to JSON Document Store

### ISSUE THREAD

**Issue by dgcaron** [SAP/kafka-connect-sap#14]
we are trying to get data from a NoSQL Database into Hana and it seems to be the most straightforward to write to a JSON Document Store in Hana. https://blogs.sap.com/2018/04/18/the-sap-hana-json-document-store-introduction-part-1/. Is there any chance this will be supported in the near future?

**Comment by sbcd90** [comment]
Hello @dgcaron ,
This is a WIP & should be available soon.
