### ISSUE TITLE
Offset deserialization error

### ISSUE THREAD

**Issue by imatmati** [SAP/kafka-connect-sap#16]
Hi,

When I use incrementing mode, I got errors when I restart the connector after some previous consumption. This is the error message : 

> ERROR CRITICAL: Failed to deserialize offset data when getting offsets for task with namespace kafka-connect-source. No value for this data will be returned, which may break the task or cause it to skip some data. This could either be due to an error in the connector implementation or incompatible schema. (org.apache.kafka.connect.storage.OffsetStorageReaderImpl:102)
> org.apache.kafka.connect.errors.DataException: Offsets must be specified as a Map

I use Kafka_2.11-0.10.1.0. Thanks a lot for any information and have a nice day.

**Comment by elakito** [comment]
I'm closing this ticket, which was unfortunately not attended earlier. If the problem persists with the current version, please reopen it. Thanks.
