### ISSUE TITLE
using incrementing mode with CreateDate give an error

### ISSUE THREAD

**Issue by Sano123456** [SAP/kafka-connect-sap#17]
Hi
i am using key incrementing mode and CreateDate the standard SAP column and i am getting this error
Caused by: java.util.NoSuchElementException: key not found: CreateDate

{
    "name": "sap",
    "config": {
        "connector.class": "com.sap.kafka.connect.source.hana.HANASourceConnector",
        "tasks.max": "10",
        "topics": "mytopic",
        "mode":"incrementing",
        "auto.offset.reset":"latest",
        "group.id":"589f5ff5-1c43-46f4-bdd3-66884d61m185",
        "poll.interval.ms":"86400000",
        "mytopic.table.name":                          "\"schema\".\"table\"",
        "mytopic.poll.interval.ms":                    "86400000",
        "mytopic.incrementing.column.name":            "CreateDate"
    }
}

**Comment by igorcosta** [comment]
When you're setting up, did you set the auto.create=true

If not that's the problem, the CreateDate if doesn't exist it will give that null point error.

**Comment by elakito** [comment]
@Sano123456 I suspect the column simply doesn't exist. And if that is indeed the case, the current version will report a more readable error "The Incrementing column is not found in the table". Have you checked the table? I'm closing the ticket. If your table has the column and you are enchanting some error, please reopen this ticket and attach the trace.
Thanks.
