### ISSUE TITLE
Can we have timestamp+incrementing mode in the source connect

### ISSUE THREAD

**Issue by viprud** [SAP/kafka-connect-sap#22]
All the other jdbc source connectors support the timestamp+incrementing mode, can we have the same feature in the SAP HANA source connect?

**Comment by lucasmaffazioli** [comment]
Does this feature exists?

**Comment by viprud** [comment]
> 
> 
> Does this feature exists?

No, JDBC connector supports SAP and it has that feature,  so you can use that connector.
