### ISSUE TITLE
After connector restarts all data is ingested from scratch

### ISSUE THREAD

**Issue by denisvlah** [SAP/kafka-connect-sap#25]
If the queyMode = "query" and the mode = "incrementing" than the offsets are saved with invalid partition name, check the following line:
https://github.com/SAP/kafka-connect-sap/blob/103e44f69e583b18aac7ee704fc2d03c54ceb7fa/src/main/scala/com/sap/kafka/connect/source/querier/IncrColTableQuerier.scala#L68

After connector restart it will try to get last committed offset with wrong key and restart ingestion from scratch.

**Comment by sbcd90** [comment]
@denisvlah , can you please create a PR?
