### ISSUE TITLE
Link for JDBC installation in Readme is not working

### ISSUE THREAD

**Issue by lucasmaffazioli** [SAP/kafka-connect-sap#27]
This link:

http://help.sap.com/saphelp_hanaplatform/helpdata/en/ff/15928cf5594d78b841fbbe649f04b4/frameset.htm guide to access the SAP HANA Jdbc jar.

**Comment by sbcd90** [comment]
This should help: https://help.sap.com/viewer/0eec0d68141541d1b07893a39944924e/2.0.03/en-US/ff15928cf5594d78b841fbbe649f04b4.html

**Comment by lucasmaffazioli** [comment]
Thanks, this link worked.

**Comment by elakito** [comment]
replaced the link.
