### ISSUE TITLE
Does acessing jdbc.jar require license?

### ISSUE THREAD

**Issue by oguzhanaygn** [SAP/kafka-connect-sap#30]
Hi,
I'm a newbie on SAP Connectors, I'm trying to use them for a data warehouse project for the first time. I don't have enough experience on SAP either. I've following questions regarding to the task I have,

1 ) I have run mvn clean install -DskipTests command, now I have "kafka-connect-hana-1.0-SNAPSHOT.jar" jar file in my directory. But I don't really get the "Include Jdbc jar" part in the documentation. Is it also collected from this source code repo? What should I do to collect it? If the jdbc connector is apart from "kafka-connect-hana-1.0-SNAPSHOT.jar", why do need to create this jar file?

2 ) Also, as far as I understood, confluent.io doesn't give support for these connectors. Is the connector support a part of SAP License? Or do we need another license agreement for collecting jdbc.jar files and taking support?

I'd be much appreciated if I get answers to these questions :)
Thank you from now,
Best Regards.

**Comment by elakito** [comment]
Hi,
1. the JDBC driver jar is required to actually connect to an HANA instance. This jar is not needed to build kafka-connect-hana-xxx.jar but it is needed at the connector to be able to connect to the HANA instance. You can download this jar file from the public maven repository  (e.g., https://repo1.maven.org/maven2/com/sap/cloud/db/jdbc/ngdbc/2.5.49/ngdbc-2.5.49.jar). 

2. This kafka-connect-hana is a community connector with Apache License. The JDBC driver is covered by SAP Developer License Agreement https://tools.hana.ondemand.com/developer-license-3_1.txt and a copy of this file is also included in ngdbc-x.x.x-sources.jar.  You can expect to get support from SAP community SCN site or here at this GitHub repo's issues section but there is no commercial support. There is no process in providing commercial support for those projects hosted at github.com/SAP.

If you want to try out this connector, you can look at the examples. https://github.com/SAP/kafka-connect-sap/tree/master/examples
Please let me know if you need more help.
regards, aki
