### ISSUE TITLE
Sink is not working

### ISSUE THREAD

**Issue by MrJack91** [SAP/kafka-connect-sap#36]
I built the jar and want to use it with:
debezium/connect and kafka in V1.2.

It's not working. If I want to write the messages I got:
![2020-09-01_17h55_53](https://user-images.githubusercontent.com/219098/91875990-7e763f80-ec7c-11ea-9969-cf2c7b3c98bb.png)

**Comment by elakito** [comment]
kafka-connect-hana.jar uses guava.jar and Kafka 2.4.x includes this jar while kafka 2.5.x doesn't include guava.jar. That means, you will need to add e.g., guava-20.0.jar (which is included in Kafka-2.4.1's libs) into the plugin folder.

Could you try it out?

**Comment by elakito** [comment]
I updated the examples with an example using debezium https://github.com/SAP/kafka-connect-sap/tree/master/examples/persons1db

**Comment by elakito** [comment]
I'll have to look into it again. Debezium's Kafka Connect image brings in guava 27.0.1-jre into the plugin folder, so there should be no need to bring in another copy.

**Comment by elakito** [comment]
It seems guava 27.0.1-jre is only added when the schema client is used and when it is not used, you have to add it because kafka-connect-hana needs guava.

**Comment by MrJack91** [comment]
Thanks for your answer.
I'm going forward with the confluents jdbc sink. If there i got some more problems, i will continue with this sink.

**Comment by MrJack91** [comment]
Ok. I've got some more problems with the confluent sink (length of VARCHAR's is not handled).

So I tried this again. With the newest guava-29.0-jre.jar i got this error:
![2020-09-15_17h37_39](https://user-images.githubusercontent.com/219098/93232739-894fca80-f77a-11ea-92f7-66006fc41ba6.png)

Could you give me a hint?

**Comment by MrJack91** [comment]
Would be interesting, what the logicalType would be here:
https://github.com/SAP/kafka-connect-sap/blob/8d3c293d7938361427d57d07692a1544073188fc/src/main/scala/com/sap/kafka/utils/GenericSchemaBuilder.scala#L65

Anyhow: do you know the confluent jdbc sink? Which one works better. Both seems not really working for my desire (datatype support).

**Comment by elakito** [comment]
@MrJack91 The logical type error seems to be an unwanted limitation at the moment. If you are not using the schema registry, you could find the schema in the Kafka message. I suppose one of the time related logical type which is not handled in that Kafka-connect-sap's schema builder. I suppose we need to add the support for all logical types.

**Comment by elakito** [comment]
I guess the variable is set to an empty string because the schema of this particular field has no `connect.name` property as in
 ```
{
          "type": "long",
          "connect.version": 1,
          "connect.name": "org.apache.kafka.connect.data.Timestamp",
          "logicalType": "timestamp-millis"
}
```
but something like
```
{
          "type": "long",
          "logicalType": "timestamp-millis"
}
```
or
```
{
          "type": "long",
          "logicalType": "timestamp-micros"
}
```
Where does the message come from?

**Comment by MrJack91** [comment]
I stream data from MSSQL (debezium) to HANA (confluent jdbc sink), using also the confluent schema registry (with avro).
I will investigate tomorrow more time to it.
Currently i try also to generate the table with python in a own script, before the kafka sink, to skip this problem.
But I also discovered, that we have some problems with dates (they are converted to Timestamps as Int) and will arrive in HANA als Int. Thats pretty useless.
Did you ever use debezium and this sink for whole replication of different databases? It's quite a hard job... :(

**Comment by elakito** [comment]
by the way, I included the type name in the exception message of the master branch code.

**Comment by elakito** [comment]
regarding the date, Hana-source to Hana-sink, date is transferred as date.
But since date is a logical type based on int, it could be that there is an incompatibility in recognising this type information from the provided schema.
Could you look at the schema from your confluent registry? You can use http query to inspect the schema https://docs.confluent.io/current/schema-registry/develop/api.html#subjects

**Comment by MrJack91** [comment]
Thanks you again for your response. That's really awesome!

The field in the schema in avro is:
```
{
      "name": "valid_from",
      "jdbcType": 93,
      "nativeType": null,
      "typeName": "datetime2",
      "typeExpression": "datetime2",
      "charsetName": null,
      "length": 27,
      "scale": 7,
      "position": 15,
      "optional": false,
      "autoIncremented": false,
      "generated": false
},
```

The kafka schema is:
```
{
    "name": "valid_from",
    "type": {
        "connect.name": "io.debezium.time.NanoTimestamp",
        "connect.version": 1,
        "type": "long"
    }
}
```

**Comment by elakito** [comment]
Thanks for looking into this and that explains why the sink hana-connector is failing on that field. In Hana-connector, currently, only those types defined in apache kafka-connect (https://github.com/apache/kafka/tree/trunk/connect/api/src/main/java/org/apache/kafka/connect/data) are handled. This list is rather short and there is no nanoTimestamp nor microTimestamp. Debezium defines their own types (https://github.com/debezium/debezium/tree/master/debezium-core/src/main/java/io/debezium/time) and this NanoTimestamp is one of them.

I wonder if there is an option in Debezium to make the source connector only use those types defined in kafka-connect.
But in any case, we will consider adding those additional types in kafka-connect-hana so that we can indeed transfer higher precision data.

**Comment by MrJack91** [comment]
Hi Elakito

Thanks for your answer.

I can let debezium only use kafka datatypes:
```
"time.precision.mode": "connect",
```

Then i got this schema-field entry:
```
{
    "name": "valid_from",
    "type": {
        "connect.name": "org.apache.kafka.connect.data.Timestamp",
        "connect.version": 1,
        "logicalType": "timestamp-millis",
        "type": "long"
    }
}
```

I got also an error:
![image](https://user-images.githubusercontent.com/219098/94267048-396fc100-ff3b-11ea-96ae-b84b012fdba9.png)

**Comment by elakito** [comment]
@MrJack91 Cool. I didn't know there was a setting in debezium to stick to the standard type. By the way, I had a chat with someone at their google group regarding this debezium type. And I think it would be helpful to support those debezium types by mapping them to the corresponding logical types and also support other types as the associated primitive types instead of simply rejecting them.

Regarding the current error, has there been any change to the table schema or does your scenario expect its its schema to be changed? The hana connector currently doesn't support any schema change and this feature needs to be added.

**Comment by MrJack91** [comment]
@elakito Sorry for writing that long not back.

Since the last version in September I've to update the AVRO converter plugin. So far it works again like before.

I want not to use the auto evolution option, only the initial create of the tables.

Currently i have two errors:
- varchar(x) is fixed to varchar(1000)
- the create table statement (initial) has two times the id field

## varchar(x) is fixed to varchar(1000)
Varchar(x) will be converted to a fix varchar(1000). independent of the source varchar length.
this should be generic here: https://github.com/SAP/kafka-connect-sap/blob/0e1fecabc733c508a8eb42bfa0786052b99e2c5c/src/main/scala/com/sap/kafka/client/hana/HANAJdbcClient.scala#L163
This is the same behaviour like in the jdbc-sink from confluent.


## table creation has two times the id field inside
Then in the create statement, there is two times the id field inside.
```sql
CREATE COLUMN TABLE "NRT_MEONA"."MHA_TEST_DATATYPE" ("id" INTEGER NOT NULL, "id" INTEGER NOT NULL, "chart_configuration" VARCHAR(1000) NOT NULL, "valid_from" TIMESTAMP NOT NULL, "__null_ts_ms" BIGINT NULL, "__deleted" VARCHAR(1000) NULL);
```

```log
2020-12-17 08:11:19,631 INFO   ||  Creating table:MHA_TEST_DATATYPE with SQL: CREATE COLUMN TABLE "NRT_MEONA"."MHA_TEST_DATATYPE" ("id" INTEGER NOT NULL, "id" INTEGER NOT NULL, "chart_configuration" VARCHAR(1000) NOT NULL, "valid_from" TIMESTAMP NOT NULL, "__null_ts_ms" BIGINT NULL, "__deleted" VARCHAR(1000) NULL)    [com.sap.kafka.client.hana.HANAJdbcClient]
2020-12-17 08:11:19,674 ERROR  ||  Error during table creation   [com.sap.kafka.client.hana.HANAJdbcClient]
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [272] (at 53): duplicate column name: id: line 1 col 54 (at pos 53)
        at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:195)
        at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:45)
        at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:837)
        at com.sap.db.jdbc.packet.HReplyPacket.getSQLExceptionChain(HReplyPacket.java:158)
        at com.sap.db.jdbc.packet.HPartInfo.getSQLExceptionChain(HPartInfo.java:39)
        at com.sap.db.jdbc.ConnectionSapDB._receive(ConnectionSapDB.java:4476)
        at com.sap.db.jdbc.ConnectionSapDB.exchange(ConnectionSapDB.java:1876)
        at com.sap.db.jdbc.StatementSapDB._executeDirect(StatementSapDB.java:1827)
        at com.sap.db.jdbc.StatementSapDB._execute(StatementSapDB.java:1801)
        at com.sap.db.jdbc.StatementSapDB._execute(StatementSapDB.java:1762)
        at com.sap.db.jdbc.StatementSapDB.execute(StatementSapDB.java:583)
        at com.sap.kafka.client.hana.HANAJdbcClient.$anonfun$createTable$2(HANAJdbcClient.scala:189)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at scala.util.Try$.apply(Try.scala:213)
        at com.sap.kafka.client.hana.HANAJdbcClient.$anonfun$createTable$1(HANAJdbcClient.scala:189)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at com.sap.kafka.utils.ExecuteWithExceptions$.apply(ExecuteWithExceptions.scala:40)
        at com.sap.kafka.client.hana.HANAJdbcClient.createTable(HANAJdbcClient.scala:158)
        at com.sap.kafka.connect.sink.hana.HANASinkRecordsCollector.add(HANASinkRecordsCollector.scala:144)
        at com.sap.kafka.connect.sink.hana.HANAWriter.$anonfun$write$2(HANAWriter.scala:61)
        at com.sap.kafka.connect.sink.hana.HANAWriter.$anonfun$write$2$adapted(HANAWriter.scala:44)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:912)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:154)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:911)
        at com.sap.kafka.connect.sink.hana.HANAWriter.write(HANAWriter.scala:44)
        at com.sap.kafka.connect.sink.GenericSinkTask.put(GenericSinkTask.scala:45)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

This is my sink config:
```json
{
    "name": "s-meona-mha-hana",
    "config": {
        "connector.class": "com.sap.kafka.connect.sink.hana.HANASinkConnector",
        "tasks.max": "1",
        "topics": "meona_mha_1.dbo.mha_test_datatype",
        "connection.url": "xx",
        "connection.user": "xx",
        "connection.password": "xx",


        "meona_mha_1.dbo.mha_test_datatype.table.name": "\"NRT_MEONA\".\"MHA_TEST_DATATYPE\"",
        "pk.mode": "record_key",
        "pk.fields": "id",
        
        "auto.create": "true",
        "auto.evolve": "true",

        "transforms": "unwrap",
        "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
        "transforms.unwrap.drop.tombstones": "false",
        "key.converter": "io.confluent.connect.avro.AvroConverter",
        "key.converter.schema.registry.url": "http://schema-registry:8081",
        "value.converter": "io.confluent.connect.avro.AvroConverter",
        "value.converter.schema.registry.url": "http://schema-registry:8081",
        "delete.enabled": "true"
    }
}
```

Would be awesome for some help.

Btw: pretty the same configuration is working with the jdbc-sink from confluent. Because of that, if think the double id-field is a bug.

**Comment by elakito** [comment]
@MrJack91 thanks for the update. The varchar limit is actually 5000 in HANA. Using '*' or setting a larger value will be rejected by HANA. https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.03/en-US/a33f7884b0c14c00b1a76ecd8af5feca.html

We can increase it to 5000. Is it okay for you use case or does it need to be configurable so that a smaller value can be used for a specific connector instance?

Regarding the duplicate ID, I'll look into it. I remember looking into a similar problem...

**Comment by elakito** [comment]
For the second issue, it looks like the statement builder code in hana-connector is broken and it leads to this problem when the message contains a key schema.

**Comment by MrJack91** [comment]
@elakito Thanks for your answer. Amazing answer time.

> @MrJack91 thanks for the update. The varchar limit is actually 5000 in HANA. Using '*' or setting a larger value will be rejected by HANA. https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.03/en-US/a33f7884b0c14c00b1a76ecd8af5feca.html
> 
> We can increase it to 5000. Is it okay for you use case or does it need to be configurable so that a smaller value can be used for a specific connector instance?
> 
> Regarding the duplicate ID, I'll look into it. I remember looking into a similar problem...

I think best would be:
- use the exact same type (varchar with the **same length**)
- if this is not possible, use the next bigger: e.g. hana text datatype
  - if needed, this can be reduced manually later anyway. but it's working then generally.

I did something similar with a python module, but then i need to run this first. Would be better to have only one piece of code.

In general it would be also nice, to overwrite the default datatype mapping via configuration. But sure, this is enhanced, but would be very useful. We use default datatype depending on the original source system.

About the second issue: sounds good, that you find something. Is it possible to fix?

**Comment by elakito** [comment]
@MrJack91 For the varchar size, is your avro schema a custom length/size property? Avro itself doesn't define the size property. So, we have a few options
- OPT0 for now, I think we'll set it to 5000. For the future, we can consider one of the below options.
- OPT1 if there is a widely used extension property for the size, using this value.
- OPT2 providing a mapping configuration to read the size extension value from the schema (if different schemas use different properties for the size)
- OPT3 introducing a parameter xxxxx.char.max per connector to set its default.
- OPT4 introducing a way to configure per char-based column

For the duplicate column names, I think it is fixed with #61

**Comment by MrJack91** [comment]
@elakito Ah I use debezium, there you have the schema-change-topic:
https://debezium.io/documentation/reference/1.3/connectors/sqlserver.html#_schema_change_topic
There you have additional informations. Maybe it's a common use of your connector, with debezium.

And yes, with OPT0 I will be happy.
And for generic use, OPT4 would be really awesome.

I will test the new version in January. Thanks a lot.

Wish you nice days to celebrate!

**Comment by elakito** [comment]
@MrJack91 thank you and I wish you nice holidays.

**Comment by elakito** [comment]
please try https://github.com/SAP/kafka-connect-sap/releases/tag/0.9.0
the varchar problem and the duplicate column problems are fixed in this version.

**Comment by MrJack91** [comment]
Hi @elakito 
Thanks for the new version I tested it.
Used the version kafka-connector-hana_2.12-0.9.0.jar. (With the other one (Scala 2.13), I couldn't start the broker again. )

It's working so far. Both mentioned errors where fixed (multiple id fields and too short data type). Thanks!

But is it true, that there is no upsert method?
So updates and deletes are not supported in the sink?
I've the messages in kafka:
![image](https://user-images.githubusercontent.com/219098/103876174-9f8be880-50d3-11eb-8e1e-fba6886b3b1e.png)

Regards
Michael

**Comment by elakito** [comment]
@MrJack91 thanks for verifying the fix.
Regarding the sink insertion mode, it currently only supports INSERT. We can make this configurable to use UPSERT. For the deletion, we could also add the logic but I'll look into it.

**Comment by elakito** [comment]
@MrJack91 I think I got the upsert and delete working. I have an example scenario mysql->hana using debezium. I just only need to add some unit tests and then upload the change.

**Comment by elakito** [comment]
upsert/delete should work now. You can look at examples/inventory7db example. It would be great if you can verify it with your use case. Thanks.

**Comment by elakito** [comment]
@MrJack91 I'm closing this ticket.
