### ISSUE TITLE
when using incrementing mode,update and delete can not captured

### ISSUE THREAD

**Issue by chendrp** [SAP/kafka-connect-sap#40]
when using incrementing mode,update and delete can not captured,how can we get the whole change data of hana table? 

 "name": "sap-hana-source_2",  
  "config": {
  "connector.class":"com.sap.kafka.connect.source.hana.HANASourceConnector",
  "tasks.max":"1",
  "topics":"sap-hana-source_2",
  "connection.url":"jdbc:sap://10.*.*.*:30215/",
  "connection.user":"sap*****",
  "connection.password":"******",
  "mode":"incrementing",
  "sap-hana-source_2.incrementing.column.name":"DEPTNO",
  "sap-hana-source_2.table.name":"\"SAPHANADB\".\"DEPT2\""

**Comment by elakito** [comment]
To capture such events, the driver supporting the CDC mode would be required. We would like to have this feature but currently, the connector uses the jdbc driver and this feature is not supported.

**Comment by twonly** [comment]
> To capture such events, the driver supporting the CDC mode would be required. We would like to have this feature but currently, the connector uses the jdbc driver and this feature is not supported.

Hi Elakito, does that mean this hana connect (incrementing mode) only works for "INSERT"?

**Comment by twonly** [comment]
@elakito , thanks again for this clarification. AFAIK HANA does not provide an official CDC interface like BINLOG in other DBs. You mentioned this connector (supporting CDC) is being developed, does that mean SAP will provide some tool like OGG does?

**Comment by elakito** [comment]
https://github.com/SAP/kafka-connect-sap/issues/74
