### ISSUE TITLE
records not reaching the topic

### ISSUE THREAD

**Issue by dtstefanov** [SAP/kafka-connect-sap#42]
Hello everyone,

I am running kafka and zookeeper on local ubuntu wsl. Both servers are running fine and terminal messages can be transferred without any issues. However, when trying to test the hana connector I cannot see anything coming for the topic in the console consumer neither in the target hana. Any guidance is greatly appreciated.

![image](https://user-images.githubusercontent.com/29522641/95589021-d6a71b00-0a4c-11eb-909a-093fa298b1fb.png)

connect-hana-source-1.properties
![image](https://user-images.githubusercontent.com/29522641/95590681-06572280-0a4f-11eb-8205-1f5f3010a340.png)

connect-hana-sink-1.properties
![image](https://user-images.githubusercontent.com/29522641/95590540-dad43800-0a4e-11eb-8e35-f5ba34388607.png)

**Comment by elakito** [comment]
It looks like you are running the connector in the standalone mode. In that case, you should see the trace output from the connector. Which version of Kafka are you using?

**Comment by dsteffanov** [comment]
Hey, I am running kafka 2.13-2.6.0 and the connector in standalone mode.

**Comment by elakito** [comment]
If you are running it in standalone mode, you should see some errors when the connector is started. Could you paste the log at the startup?

**Comment by elakito** [comment]
@dsteffanov By the way, did you build the kafka-connect-hana.jar with scala 13 on your own? The current mvn install will use scala 2.12. You should be able to use kafka-hana-connect.jar with kafka 2.12-2.6.0.

**Comment by elakito** [comment]
@dtstefanov I just created a work in progress version of scala 2.13 build at https://github.com/elakito/kafka-connect-sap/tree/ay-scala213_compat
`mvn -Pscala_2.13 clean install` will create kafka-connector-hana_2.13-1.0.0-SNAPSHOT.jar in target which can be used with kafka 2.13-2.6.x. We'll need to restructure the folders to generate 2.12 and 2.13 jars in one build

**Comment by elakito** [comment]
I am deleting branch ay-scala21_compat mentioned above in favour of this PR https://github.com/SAP/kafka-connect-sap/pull/60

**Comment by elakito** [comment]
fixed with https://github.com/SAP/kafka-connect-sap/releases/tag/0.9.0
please try the scala-2.13 version.
