### ISSUE TITLE
kafka 2.11-1.1.0

### ISSUE THREAD

**Issue by Lipeng522** [SAP/kafka-connect-sap#43]
Hi,author,I have a question.
My company's kafka's version is kafka 2.11-1.1.0, when I changed the version in Pom, there exist some issue,mayde compatibility issues.
issue occur in: com.sap.kafka.client.hana.AbstractHANAPartitionLoader
issue loacation:
 private[hana] def prepareInsertIntoCollStmt(collectionName: String, recordMap: Map[String, AnyRef]): String = {
    val mapper = new ObjectMapper()
    //DefaultScalaModule can't not found
    mapper.registerModule(DefaultScalaModule)
    log.info(s"""INSERT INTO $collectionName VALUES ('${mapper.writeValueAsString(recordMap)}')""")
    s"""INSERT INTO $collectionName VALUES ('${mapper.writeValueAsString(recordMap)}')"""
  }

when  I changed kafka version from 1.1.0 to 2.3.0, no issue occur.
Can you help me and tell me how to tune the code, thank you

**Comment by elakito** [comment]
If you want to build an older jars file, you can check out the repo at https://github.com/SAP/kafka-connect-sap/tree/103e44f
That used version 0.11.0.3. We don't have a version that used version 1.1.0.

**Comment by elakito** [comment]
@Lipeng522 I am closing this ticket as won't fix. If you need scala-2.11/kafka-1.1.0 compatible connector, you will need to try an older version as suggested above.
