### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by remi-sap** [SAP/kafka-connect-sap#6]
Hello,
Could you please mention that the connector doesn't work with json.
It only works with the Confluence stack: avro + schema registry.

Thanks.

**Comment by elakito** [comment]
@remi-sap actually, if the connector should be using json by default as that is the default used by the default connect-xxxxxx.properties. Maybe you installed the connector to the connect instance which used confluence avro+schema registry use. But you could still override the setting in the connector's configuration. This worked always that way. The current version has various examples with json, avro, with or without  a schema registry (confluence or apicurio).
