### ISSUE TITLE
insert.mode UPSERT not working and same data would be inserted several times

### ISSUE THREAD

**Issue by twonly** [SAP/kafka-connect-sap#65]
Hi team, 

I observed that when I restarted the connect-standalone.sh, the same full dataset from source were written again into the sink HANA. 
It looks to me that the `upsert` mode is not working. I tried making the incrementing column (ID) as and as not PRIMARY KEY, but both scenarios would be the same result. 
Moreover, if ID column is set as primary key, then restarting the connect-standalone would cause unique constraints exception and the sink worker would be killed. 

The config files for source and sink are as below, the `<topic_name>.insert.mode` is set as `upsert`
*connect-hana-sink-metadata-incr.properties:*
auto.create=true
topics=topic_metadata_incr
topic_metadata_incr.table.name="HDB_METADATA"."SCHEMA_DISK_SIZE_1"
topic_metadata_incr.poll.interval.ms=5000
*topic_metadata_incr.insert.mode=upsert*

*connect-hana-source-metadata-incr.properties:*
topics=topic_metadata_incr
topic_metadata_incr.table.name="HDB_METADATA"."SCHEMA_DISK_SIZE"
topic_metadata_incr.incrementing.column.name=ID
topic_metadata_incr.poll.interval.ms=5000
mode=incrementing

**Comment by twonly** [comment]
At first glance I suspect it's because the ID column is not PRIMARY KEY as the code in AbstractHANAPartitionLoader prepare the UPSERT statement "WITH PRIMARY KEY". However, after setting the column as PK, it still does not work. 
https://github.com/SAP/kafka-connect-sap/blob/645ab1ab00ce802a6753f02ba18022633c5862f6/src/main/scala/com/sap/kafka/client/hana/AbstractHANAPartitionLoader.scala#L259

**Comment by twonly** [comment]
After updating below config in connect-standalone.properties, truncating the sink table, deleting the topic and `rm /tmp/connect.offsets`, it seems that after restarting the connect, it can continue to work without re-reading all the data in the source table.
`consumer.auto.offset.reset=latest`

**However, it can not explain why the UPSERT mode did not work.**

**Comment by elakito** [comment]
@twonly Did you recreate the table after fixing the configuration? And how is your pk.fields and pk.mode are configured? 

The incrementing column at the source should be used for the incrementing purpose (like using just an incremental index or timestamp) so that the source connector can pull only the newer records at each poll. For upsert at the sink connector, you should have another column that uniquely identifies the record so that the upsert will overwrite this record. I don't know what is not working. Could you describe the problem with some small concrete example? Thanks.

**Comment by twonly** [comment]
@elakito After fixing the configuration (adding `consumer.auto.offset.reset=latest`), I truncated the sink table and left the source table as it was (no recreation, no truncation...), and since then, things look as expected, no matter I restarted the connect (both source and sink , only either of them), the sink can poll the incrementing data from source. However, from the HANA SQL Cache, I can only see INSERT but no UPSERT statements.

The source table has an incrementing column `ID - BIGINT type`, which is also defined as primary key and NOT NULL, and generated by default as IDENTITY. (Previously the UPDATE_TIME column - TIMESTAMP type - was used, but it's not strictly unique and the incrementing mode did not work as expected, so I added this new column ID)
By "For upsert at the sink connector, you should have another column that uniquely identifies the record so that the upsert will overwrite this record.", do you mean I need to specify the incrementing column as well in the sink property? (like <topic>.incrementing.column.name)
FYI, the sink table has same structure as source table, except that the ID column is not generated by default, but by being inserted/upserted by KAFKA.

I did not go through the source code yet, so it would be great if you can explain a little about how the incrementing work in source - like fetching the latest message in the topic and then retrieving all newer data from source by comparing the incrementing column (which also requires the incrementing column should be monotonically increasing?)

The source/sink properties files are as below:
**SOURCE**
`name=topic_metadata_source_incr
connector.class=com.sap.kafka.connect.source.hana.HANASourceConnector
tasks.max=1
topics=topic_metadata_incr
connection.url=jdbc:sap://localhost:31115/
connection.user=user
connection.password="pass"
topic_metadata_incr.table.name="HDB_METADATA"."SCHEMA_DISK_SIZE"
topic_metadata_incr.incrementing.column.name=ID
#queryMode=query
topic_metadata_incr.poll.interval.ms=5000
#topic_metadata_incr.query=SELECT ID, UPDATE_TIME, SID, SCHEMA_NAME, DISK_SIZE_GB FROM HDB_METADATA.SCHEMA_DISK_SIZE
batch.max.rows=100000
mode=incrementing`

**SINK**
`name=topic_metadata_sink_incr
connector.class=com.sap.kafka.connect.sink.hana.HANASinkConnector
tasks.max=1
topics=topic_metadata_incr
connection.url=jdbc:sap://localhost:31115/
connection.user=user
connection.password="pass"
auto.create=true
topic_metadata_incr.table.name="HDB_METADATA"."SCHEMA_DISK_SIZE1"
topic_metadata_incr.poll.interval.ms=5000
topic_metadata_incr.insert.mode=upsert`

**Comment by elakito** [comment]
@twonly One of the problems with your configuration is that you can't use the incrementing column that generates a unique value at the source connector as the primary key used at the sink connector because there won't be any upserts/updates in that case, as every record received will have a unique primary key. So to achieve the desired upsert effect at the sink connector, you need to choose the primary key appropriately. For the source connector, any column can be used as the incrementing column. This column is used in the select's where clause to load those records having only the newer/greater values.

This column could be a primary key for the source table. But in that case, any update on that record happening on the source table won't be recognised as a new record because it has a used old ID. So, I don't know what you want to transfer from the source table to the sink table in your scenario. One possible scenario for such incrementing source -> upsert-sink scenario would be to have the source table having some monotonically increasing column used as the incrementing column and some column like deviceID and the sink table having deviceID as the primary key so that the sink table has the device's current state.

Regarding the upsert statement not observed in the cache, are you sure you are using the current master version? The upsert handling is only in the master branch. By the way, if you use the INFO log level, you should see the created prepared statements in the log. The parameter names in your configuration seem to be correct.

**Comment by twonly** [comment]
@elakito You are right, I used to put the column ID in Sink Table as unique generated key but then realized the problem you just mentioned, so I just kept it as primary key but no longer auto generated as this value would also be coming from the Source. 

In my scenario, just trying kafka-connect-sap with HANA integration and see how it work and will explore more scenarios. 

If the current Source Connector can only capture the new inserted data by using the incrementing column (monotonically increasing) then the use case might be limited. 
More specifically in the current configuration, I am replicating the source table to the sink table using incrementing mode, and wanna see if new data can be correctly inserted/upserted into the sink table. As I am using the same column (ID in this case) as the primary key and also the incrementing column, I think no the INSERT would have the same effect as UPSERT, as update on the existing record (PK also the auto generated column would not be updated) would not be captured. 
*previously* you mentioned a CDC-like source connector is being developed, do you have release plan on this? 

Regarding the LOG LEVEL, i did not change the configuration and did not see prepared statement from the log (printing in screen) either. Would you suggest which config properties should I modify to see this? The standalone connect itself or the connector's properties file? Thanks.

**Comment by elakito** [comment]
> @elakito You are right, I used to put the column ID in Sink Table as unique generated key but then realized the problem you just mentioned, so I just kept it as primary key but no longer auto generated as this value would also be coming from the Source.
> 
> In my scenario, just trying kafka-connect-sap with HANA integration and see how it work and will explore more scenarios.

That sounds good. I am looking forward to hearing your feedback.

> 
> If the current Source Connector can only capture the new inserted data by using the incrementing column (monotonically increasing) then the use case might be limited.

Yes. This point was raised several times.

> More specifically in the current configuration, I am replicating the source table to the sink table using incrementing mode, and wanna see if new data can be correctly inserted/upserted into the sink table. As I am using the same column (ID in this case) as the primary key and also the incrementing column, I think no the INSERT would have the same effect as UPSERT, as update on the existing record (PK also the auto generated column would not be updated) would not be captured.

For table replication, the incrementing column approach will work partially (i.e supporting only updates but no deletes), if the table has a unique non-primary column (e.g., incremental number or timestamp) used as the incremental column and another column serving as the primary key column.

> _previously_ you mentioned a CDC-like source connector is being developed, do you have release plan on this?

This feature will require the use of another jar file which is currently not covered by SAP Developer License (under which ngdbc.jar is covered). Therefore, there are some questions remaining, regarding how we can provide this connector. We can update you as soon as we have more information.

> 
> Regarding the LOG LEVEL, i did not change the configuration and did not see prepared statement from the log (printing in screen) either. Would you suggest which config properties should I modify to see this? The standalone connect itself or the connector's properties file? Thanks.

The standard connect setting logs INFO entries and the version of the connector was supposed to be printed. But I noticed a few days ago that the version was printed and had to fix it with https://github.com/SAP/kafka-connect-sap/pull/67.

Where did you get kafka-connector-hana_xxxx.jar? As the upsert change is only in master, you need to build the jar on your own or get one from someone who built it from master.

regards, aki

**Comment by elakito** [comment]
@twonly I'm closing this ticket as the question originally asked has been clarified and it has been inactive. If you encounter other problems, please open a specific ticket. Thanks.
