### ISSUE TITLE
Connnector skips parts of data in incrementing mode

### ISSUE THREAD

**Issue by DmitryTaliuk** [SAP/kafka-connect-sap#72]
I used connector to get data from SAP HANA tables in both `bulk `and `incrementing `modes with default `batch.max.rows` parameter (100).
Table consists more then 7400 records and in `bulk `mode it is transferred in the Kafka topic normally and periodically with delay. 
But in `incrementing` mode I found next issue - connector gets 100 records from the table, transfers them to topic. Then it skips 100 records, gets next 100, skips 200, gets 100, skips 300, gets 100 and so on. As result only about 1400 record is saved in the Kafka topic instead 7400.
May be somebody got deals with similar problem?

**Comment by elakito** [comment]
@DmitryTaliuk it looks like the incremental mode is not handling the chunked fetching that is supported by the bulk mode. Let me have a look...

**Comment by elakito** [comment]
@DmitryTaliuk the fix has been merged to master.

**Comment by DmitryTaliuk** [comment]
Thank you. I'll test it and report about result.

**Comment by DmitryTaliuk** [comment]
Incrementing mode is working fine for now. @elakito Thank you very much again.
If you have no objections, I'll close the issue.

**Comment by elakito** [comment]
@DmitryTaliuk thanks for the validation.
