### ISSUE TITLE
The connector is not very stable

### ISSUE THREAD

**Issue by Wangddawei** [SAP/kafka-connect-sap#76]
Use triggers to supplement the defects of insert / delete. According to the types of integer, float, decimal and datetime that can be used on the official website. However, there are many strange things in the process of testing. For example, if multiple tables have the same data type field as the growth field, some tables will report errors. The error information is as follows. Just change the field name, or field location, the data type will not change. Also, the use of timestamp fields is uncertain. What's more difficult to understand is that we don't know which time is OK again. After testing this situation for many times, we haven't found out the specific reason. Please explain. thanks!
![image](https://user-images.githubusercontent.com/52993046/110592980-eec6c600-81b5-11eb-9340-74b47403f58a.png)

**Comment by Wangddawei** [comment]
![Uploading image.png…]()

**Comment by Wangddawei** [comment]
![image](https://user-images.githubusercontent.com/52993046/110601088-8c72c300-81bf-11eb-9480-b1c888980799.png)

**Comment by elakito** [comment]
@Wangddawei It is not clear to me which problem you have. The first screenshot shows that you configured the incrementing column OPT_TPYE and this column was not found in the source table. The second screenshot shows that you configured column OTIME as the incrementing column. So, apparently these two screenshots are not from the same scenario. In addition,  you described that you have several tables with the same column name and type that you want to use as the incrementing column, how is this column is named?

Could you describe one problem at a time and attach the text logs (with some confidential info deleted) of that specific problem and not screenshots please.

regards, aki

**Comment by elakito** [comment]
I am closing this ticket as it has been a while since the above comment was posted.
