### ISSUE TITLE
Clarifications on how to use queryMode

### ISSUE THREAD

**Issue by vilterpanitz** [SAP/kafka-connect-sap#8]
Hello there,

I'm trying to setup a source hana connector with queryMode. Have tried a few options but I'm not getting this properly configured.

Can you drop here some example of how to use it and get it proper configured?

Thanks

**Comment by vilterpanitz** [comment]
Hi Guys, I just figured this out.

When using query mode ` "queryMode":"query"`, it's also required to have a `query` parameter defined. This query parameter needs to be prepended by TopicName.

And in the event that you are using `incrementing.column.name` property together, you can omit it from your `where` statement.

Can I ask you to update the README file to make it clear?

**Comment by lhoshid** [comment]
Hi, can you send your example source connector using query mode as i am running into similar issue?  thanks!
Lisa

**Comment by Mahi4089** [comment]
@vilterpanitz Could you please provide your source connector using query mode as i am also trying to do the same.
Any help would be appreciated.

**Comment by vilterpanitz** [comment]
Hi @Mahi4089 , its being a long time I worked on this connector and I'm not at the company I worked for on that time, so I can't even have a look to remember the whole config. Maybe you wanna add a snippet of your connector config here. If I can't help, maybe others can shed some light
