### ISSUE TITLE
Question: Can this connector be used for SAP AFS/R3

### ISSUE THREAD

**Issue by dgoyal1504** [SAP/kafka-connect-sap#81]
I need to connect SAP AFS with Kafka (Source as well as producer). Can this connector be used as an intermediary?

**Comment by elakito** [comment]
It sounds like you just want to transfer data between AFS and Kafka.  This Hana connector may be used if your data resides in HANA in somewhat consumable way.

I don't know what integration options are available at AFS and whether other SAP integration products (e.g., CPI, which is based on Apache Camel) are currently used to transfer data to and from AFS to another system. Depending on what integration options are available at AFS, maybe Apache Camel's Kafka connector may be a more appropriate way to transfer data to and from Kafka. You can use this Hana connector when the data will go to or come from Hana.
